### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by gonjat** [ta264/Lidarr.Plugin.Deemix#1]
How does a person install this? drop it all in the root of lidarr? I cant find anything about lidarr plugins.
TIA

**Comment by youegraillot** [comment]
Got the same question and then made a docker image : https://github.com/youegraillot/lidarr-on-steroids

**Comment by l0l67** [comment]
**In Lidarr:**
1. Settings -> General -> Enable "Show Advanced" -> Plugins -> change Branch to "plugins"
2. System -> Updates -> Update
3. System -> Plugins -> Paste "https://github.com/ta264/Lidarr.Plugin.Deemix" into the Field -> press install
4. Deemix should now be available as Indexer / Download client

**On the same Machine:**

5. Install https://gitlab.com/Bockiii/deemix-docker

**In Lidarr:**

6. set up the Deemix Indexer / Download Client
7. Done

**Comment by Mange** [comment]
There's no plugin section under Settings -> General, either with or without advanced settings, for me.

I suppose it might be under the "Updates" headline, which just contains a single paragraph about updates being disabled when running Lidarr in a container. Is it supposed to be there?

**Comment by l0l67** [comment]
I am on the official version, installed via this Documentation: https://wiki.servarr.com/lidarr/installation#linux

![grafik](https://user-images.githubusercontent.com/63732527/185616040-8d88af93-fb90-497e-a8fd-7eac60bf211d.png)

**Comment by l0l67** [comment]
> "Updates" headline, which just contains a single paragraph about updates being disabled when running Lidarr in a container.

It might be possible that you cant change the Branch in a docker container
Running Lidarr in docker i had success with the image from @youegraillot, wich does essentialy the same afaik

**Comment by ta264** [comment]
Please don't use this.  There is a lot of bad advice above.  This is for testing by users I have spoken to and given direction to.  For everyone else, please be patient until plugin support is merged into mainline lidarr.
